apiVersion: v1
kind: Namespace
metadata:
  name: gitops-lab

---
apiVersion: v1
kind: Service
metadata:
  name: open-data-service
  namespace: gitops-lab
  labels:
    app: open-data-web

spec:
  selector:
    app: open-data-web

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007

  type: NodePort
