name: Python CI Pipeline (Matrix)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      module:
        description: "Оберіть модуль для запуску (або 'all')"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - data_load
          - data_quality_analysis
          - data_research
          - visualization

jobs:
  run-modules:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        module: [data_load, data_quality_analysis, data_research, visualization]

    steps:
      - name: Checkout code
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.module }}
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        run: |
          mkdir -p artifacts/${{ matrix.module }}
          python src/${{ matrix.module }}.py > artifacts/${{ matrix.module }}/run.log 2>&1

      - name: Upload Artifacts
        if: ${{ !cancelled() && (github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module) }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.module }}
          path: artifacts/${{ matrix.module }}