name: Python CI Pipeline (Matrix)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      module:
        description: "Оберіть модуль для запуску (або 'all')"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - data_load
          - data_quality_analysis
          - data_research
          - visualization

jobs:
  run-modules:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        module: [data_load, data_quality_analysis, data_research, visualization]

    steps:
      - name: Checkout code
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        uses: actions/checkout@v4

      - name: Install dependencies
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        run: |
          # 1. Завантажуємо офіційний скрипт для встановлення/ремонту pip
          python -c "import urllib.request; urllib.request.urlretrieve('https://bootstrap.pypa.io/get-pip.py', 'get-pip.py')"
          
          # 2. Встановлюємо робочу версію pip для Python 3.13
          python get-pip.py
          
          # 3. Встановлюємо залежності з вашого файлу
          python -m pip install -r requirements.txt

      - name: Run ${{ matrix.module }}
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module }}
        run: |
          # Створюємо папку командою, яку 100% розуміє Windows
          mkdir -Force artifacts/${{ matrix.module }}
          
          # Запускаємо скрипт
          python src/${{ matrix.module }}.py

      - name: Upload Artifacts
        if: ${{ !cancelled() && (github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module) }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.module }}
          path: artifacts/${{ matrix.module }}